from . import allocations
from . import product_template
from . import maintenance_equipment
from . import maintenance_request
from . import damage_details
from . import maintenance_checklist
from . import maintenance_components
from . import project_task
from . import stock_picking
from . import product_product
from . import account_move
from . import equipment_transfer_wizard